---
driver:
  name: default

platforms:
  - name: ubi10

provisioner:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - cleanup
    - destroy
