---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    sat_server: "{{ lookup('ansible.builtin.file', '/etc/secret/satellite-secret/SATELLITE_URL', default='No Satellite Configured') }}"
    activation_key: "{{ lookup('ansible.builtin.file', '/etc/secret/satellite-secret/SATELLITE_KEY_10', default='No Activation Key Configured') }}"
    sat_org: "{{ lookup('ansible.builtin.file', '/etc/secret/satellite-secret/SATELLITE_ORG', default='No Satellite Organization Configured') }}"

  tasks:
    - name: Disable ubi repos
      ansible.builtin.file:
        path: /etc/yum.repos.d/ubi.repo
        state: absent

    - name: Install katello ca consumer package
      ansible.builtin.dnf:
        name: "{{ sat_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
        state: present
        validate_certs: false
        disable_gpg_check: true

    - name: Register with Satellite
      community.general.redhat_subscription:
        state: present
        server_hostname: "{{ sat_server |urlsplit('hostname') }}"
        activationkey: "{{ activation_key }}"
        org_id: "{{ sat_org }}"
