FROM registry.access.redhat.com/ubi9/ubi-minimal

ENV HOME=/projects/home

USER 0

COPY --chown=0:0 entrypoint.sh /
COPY --chown=0:0 set-cgroups.sh /

# Install base dependencies
RUN microdnf --disableplugin=subscription-manager install -y procps-ng openssl git \
        tar gzip zip xz shadow-utils bash podman podman-docker skopeo python3-pip \
        python3-devel python3-requests jq wget which glibc-langpack-en \
        ca-certificates aardvark-dns fuse-overlayfs util-linux sudo \
        python3-libselinux java-17-openjdk-headless ; \

    # Install ansible and related tools
    pip3 install --no-cache-dir ansible-core==2.15.13 molecule==6.0.3 \
    molecule-plugins==23.6.0 ansible-lint==6.22.2 \
    ansible-builder==3.1.1 black==25.11.0 pytest==8.4.2 ; \

    # Update complete image and cleanup
    microdnf update -y ; \
    microdnf clean all

RUN echo "user:x:1000:1000:devspaces user:${HOME}:/bin/bash" >> /etc/passwd ; \
    echo "user:x:1000:" >> /etc/group ; \
    chmod 600 /etc/shadow ; \
    echo "user:*:0:0:99999:7:::" >> /etc/shadow ; \
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    echo "user ALL=NOPASSWD: /set-cgroups.sh" >> /etc/sudoers

USER 1000
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
